
##teamcity[testSuiteStarted name='Master Test Suite']

##teamcity[testSuiteStarted name='my_suite1']

##teamcity[testStarted name='my_test1']
boost/boost_test.cpp(13): check 2 == 1 failed

##teamcity[testFailed name='my_test1' message='failed' details='boost/boost_test.cpp(13): check 2 == 1 failed|n']

##teamcity[testFinished name='my_test1' duration='0']

##teamcity[testStarted name='my_test2']
boost/boost_test.cpp(19): check i == 2 failed [0 != 2]

##teamcity[testFailed name='my_test2' message='failed' details='boost/boost_test.cpp(19): check i == 2 failed [0 != 2|]|n']

##teamcity[testFinished name='my_test2' duration='0']

##teamcity[testSuiteFinished name='my_suite1']

##teamcity[testStarted name='my_test3']

##teamcity[testFinished name='my_test3' duration='0']

##teamcity[testSuiteStarted name='my_suite2']

##teamcity[testStarted name='my_test4']
boost/boost_test.cpp(36): check i == 1 failed [0 != 1]

##teamcity[testFailed name='my_test4' message='failed' details='boost/boost_test.cpp(36): check i == 1 failed [0 != 1|]|n']

##teamcity[testFinished name='my_test4' duration='0']

##teamcity[testSuiteStarted name='internal_suite']

##teamcity[testStarted name='my_test5']
boost/boost_test.cpp(44): check i == 1 failed [0 != 1]

##teamcity[testFailed name='my_test5' message='failed' details='boost/boost_test.cpp(44): check i == 1 failed [0 != 1|]|n']

##teamcity[testFinished name='my_test5' duration='0']

##teamcity[testSuiteFinished name='internal_suite']

##teamcity[testSuiteFinished name='my_suite2']

##teamcity[testStarted name='testCerr']
Hello from cerr
./boost/test/impl/results_collector.ipp(220): Test case testCerr did not check any assertions

##teamcity[testFinished name='testCerr' duration='0']

##teamcity[testStarted name='testCout']
Hello from cout
./boost/test/impl/results_collector.ipp(220): Test case testCout did not check any assertions

##teamcity[testFinished name='testCout' duration='0']

##teamcity[testStarted name='testException']
std::runtime_error: runtime exception text

##teamcity[testFailed name='testException' message='aborted' details='std::runtime_error: runtime exception text|n']

##teamcity[testFinished name='testException' duration='0']

##teamcity[testStarted name='testAssertExceptionGood']

##teamcity[testFinished name='testAssertExceptionGood' duration='0']

##teamcity[testStarted name='testAssertExceptionFail']
std::runtime_error: runtime exception text

##teamcity[testFailed name='testAssertExceptionFail' message='aborted' details='std::runtime_error: runtime exception text|n']

##teamcity[testFinished name='testAssertExceptionFail' duration='0']

##teamcity[testStarted name='testFatal']
boost/boost_test.cpp(77): bfail

##teamcity[testFailed name='testFatal' message='aborted' details='boost/boost_test.cpp(77): bfail|n']

##teamcity[testFinished name='testFatal' duration='0']

##teamcity[testStarted name='testError']
boost/boost_test.cpp(81): berror

##teamcity[testFailed name='testError' message='failed' details='boost/boost_test.cpp(81): berror|n']

##teamcity[testFinished name='testError' duration='0']

##teamcity[testStarted name='testNothing']
./boost/test/impl/results_collector.ipp(220): Test case testNothing did not check any assertions

##teamcity[testFinished name='testNothing' duration='0']

##teamcity[testSuiteFinished name='Master Test Suite']

*** 8 failures detected in test suite "Master Test Suite"
